"""The ground truth: twenty hand-built records and the expansion they must produce.

`CONVENTIONS.md` §14 makes this directory the only place LAW-DOMAIN vocabulary may appear in
tests. This module is the fixture modules 3 and 4 are held to, and it is meant to be kept
forever: it is the one artifact in the repository that states what the row-to-event
transformation should do, independently of what it does.

How the expectations were derived, and why that matters
-------------------------------------------------------
`EXPECTED_ORDER_EVENTS` and `EXPECTED_LINE_EVENTS` were written by reading each event type's
`derivation.basis` PROSE in `ontology/packs/dataco/ontology.yaml` against each row's status
columns, by hand, one order at a time. They were NOT generated by running the code and
recording what came out -- an expectation produced that way asserts only that the code is
what it is, and it agrees with any bug that was present when it was written.

They are literal sets, not predicates. A predicate here would be a second implementation of
the emission rules, and two implementations of the same idea agree with each other's
mistakes.

The twenty rows cover, deliberately:
  * an order with two lines, so occurrence deduplication has something to deduplicate;
  * every declared process variant -- happy path, review, held, fraud, cancellation before
    dispatch, stock shortfall, late delivery;
  * a shipped order still sitting at `PENDING`, which the pack's state machine does not
    admit and the real dataset contains;
  * a realised shipping duration of zero, which is the boundary of `SHIPMENT_IN_TRANSIT`;
  * one attribute disagreement between two records about one participant, so identity
    reconciliation has one conflict to reconcile and exactly one.
"""

from __future__ import annotations

from typing import Final

__all__ = [
    "EXPECTED_ATTRIBUTE_CONFLICTS",
    "EXPECTED_ENTITY_COUNTS",
    "EXPECTED_EVENT_COUNTS",
    "EXPECTED_EVENT_TOTAL",
    "EXPECTED_LINE_EVENTS",
    "EXPECTED_NEVER_EMITTED",
    "EXPECTED_ORDER_EVENTS",
    "GROUND_TRUTH_DATASET_VERSION",
    "ORDERS",
    "OrderCase",
    "rows",
]

#: A fixed, synthetic `dataset_version`. The fixture must not move when the real file or the
#: real mapping is re-pinned: this is ground truth about the TRANSFORMATION, not about the
#: published distribution.
GROUND_TRUTH_DATASET_VERSION: Final[str] = "groundtruth@0000000000000000+map0000000000000000"


class OrderCase:
    """One order in the fixture: its status columns and how many lines it carries."""

    def __init__(
        self,
        reference: int,
        order_status: str,
        delivery_status: str,
        scheduled_days: int,
        real_days: int,
        lines: int,
    ) -> None:
        """Record one order's declared shape."""
        self.reference = reference
        self.order_status = order_status
        self.delivery_status = delivery_status
        self.scheduled_days = scheduled_days
        self.real_days = real_days
        self.lines = lines


#: The fifteen orders, twenty lines between them.
ORDERS: Final[tuple[OrderCase, ...]] = (
    OrderCase(1, "COMPLETE", "Advance shipping", 4, 3, 2),
    OrderCase(2, "CLOSED", "Shipping on time", 2, 2, 2),
    OrderCase(3, "PENDING", "Advance shipping", 4, 2, 2),
    OrderCase(4, "PENDING_PAYMENT", "Advance shipping", 4, 4, 1),
    OrderCase(5, "PAYMENT_REVIEW", "Late delivery", 2, 5, 2),
    OrderCase(6, "SUSPECTED_FRAUD", "Shipping canceled", 4, 4, 1),
    OrderCase(7, "ON_HOLD", "Shipping canceled", 4, 4, 1),
    OrderCase(8, "CANCELED", "Shipping canceled", 4, 4, 1),
    OrderCase(9, "PROCESSING", "Shipping canceled", 4, 4, 1),
    OrderCase(10, "PROCESSING", "Late delivery", 1, 6, 2),
    OrderCase(11, "COMPLETE", "Shipping on time", 4, 0, 1),
    OrderCase(12, "CLOSED", "Advance shipping", 4, 1, 1),
    OrderCase(13, "COMPLETE", "Late delivery", 2, 3, 1),
    OrderCase(14, "PAYMENT_REVIEW", "Advance shipping", 4, 2, 1),
    OrderCase(15, "ON_HOLD", "Late delivery", 2, 4, 1),
)

#: The order-scoped events each order must produce, one entry per order reference.
#:
#: "Order-scoped" means the event type's participants name no line, so the order's lines
#: witness ONE occurrence between them however many there are. Hand-derived from the pack's
#: `participants` declarations and its `derivation.basis` prose.
EXPECTED_ORDER_EVENTS: Final[dict[int, frozenset[str]]] = {
    1: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_APPROVED",
            "SHIPMENT_IN_TRANSIT",
            "ORDER_COMPLETED",
        }
    ),
    2: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_APPROVED",
            "SHIPMENT_IN_TRANSIT",
            "ORDER_COMPLETED",
            "ORDER_CLOSED",
        }
    ),
    3: frozenset({"ORDER_PLACED", "SHIPMENT_IN_TRANSIT"}),
    4: frozenset({"ORDER_PLACED", "PAYMENT_REQUESTED", "SHIPMENT_IN_TRANSIT"}),
    5: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_REVIEW_OPENED",
            "SHIPMENT_IN_TRANSIT",
            "SHIPMENT_DELAYED",
        }
    ),
    6: frozenset({"ORDER_PLACED", "PAYMENT_REVIEW_OPENED", "FRAUD_SUSPECTED"}),
    7: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_FAILED",
            "PAYMENT_REVIEW_OPENED",
            "ORDER_HELD",
        }
    ),
    8: frozenset({"ORDER_PLACED"}),
    9: frozenset({"ORDER_PLACED", "PAYMENT_REQUESTED", "PAYMENT_APPROVED"}),
    10: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_APPROVED",
            "SHIPMENT_IN_TRANSIT",
            "SHIPMENT_DELAYED",
        }
    ),
    11: frozenset({"ORDER_PLACED", "PAYMENT_REQUESTED", "PAYMENT_APPROVED", "ORDER_COMPLETED"}),
    12: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_APPROVED",
            "SHIPMENT_IN_TRANSIT",
            "ORDER_COMPLETED",
            "ORDER_CLOSED",
        }
    ),
    13: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_APPROVED",
            "SHIPMENT_IN_TRANSIT",
            "SHIPMENT_DELAYED",
            "ORDER_COMPLETED",
        }
    ),
    14: frozenset(
        {"ORDER_PLACED", "PAYMENT_REQUESTED", "PAYMENT_REVIEW_OPENED", "SHIPMENT_IN_TRANSIT"}
    ),
    15: frozenset(
        {
            "ORDER_PLACED",
            "PAYMENT_REQUESTED",
            "PAYMENT_FAILED",
            "PAYMENT_REVIEW_OPENED",
            "ORDER_HELD",
            "SHIPMENT_IN_TRANSIT",
            "SHIPMENT_DELAYED",
        }
    ),
}

#: The line-scoped events each order's EVERY line must produce.
#:
#: "Line-scoped" means the event type names a line among its participants, so two lines of
#: one order are two distinct occurrences. That fan-out is the pack's declaration, not this
#: module's choice: `SHIPMENT_DISPATCHED` names `LINE` and therefore dispatches per line.
EXPECTED_LINE_EVENTS: Final[dict[int, frozenset[str]]] = {
    1: frozenset(
        {
            "INVENTORY_RESERVED",
            "ITEM_PICKED",
            "ITEM_PACKED",
            "SHIPMENT_DISPATCHED",
            "SHIPMENT_DELIVERED",
        }
    ),
    2: frozenset(
        {
            "INVENTORY_RESERVED",
            "ITEM_PICKED",
            "ITEM_PACKED",
            "SHIPMENT_DISPATCHED",
            "SHIPMENT_DELIVERED",
        }
    ),
    3: frozenset({"ITEM_PICKED", "ITEM_PACKED", "SHIPMENT_DISPATCHED", "SHIPMENT_DELIVERED"}),
    4: frozenset({"ITEM_PICKED", "ITEM_PACKED", "SHIPMENT_DISPATCHED", "SHIPMENT_DELIVERED"}),
    5: frozenset({"ITEM_PICKED", "ITEM_PACKED", "SHIPMENT_DISPATCHED", "SHIPMENT_DELIVERED"}),
    6: frozenset({"ORDER_CANCELED"}),
    7: frozenset({"ORDER_CANCELED", "INVENTORY_SHORTFALL_DETECTED"}),
    8: frozenset({"ORDER_CANCELED", "INVENTORY_SHORTFALL_DETECTED"}),
    9: frozenset({"ORDER_CANCELED", "INVENTORY_RESERVED", "INVENTORY_RELEASED"}),
    10: frozenset(
        {
            "INVENTORY_RESERVED",
            "ITEM_PICKED",
            "ITEM_PACKED",
            "SHIPMENT_DISPATCHED",
            "SHIPMENT_DELIVERED",
        }
    ),
    11: frozenset(
        {
            "INVENTORY_RESERVED",
            "ITEM_PICKED",
            "ITEM_PACKED",
            "SHIPMENT_DISPATCHED",
            "SHIPMENT_DELIVERED",
        }
    ),
    12: frozenset(
        {
            "INVENTORY_RESERVED",
            "ITEM_PICKED",
            "ITEM_PACKED",
            "SHIPMENT_DISPATCHED",
            "SHIPMENT_DELIVERED",
        }
    ),
    13: frozenset(
        {
            "INVENTORY_RESERVED",
            "ITEM_PICKED",
            "ITEM_PACKED",
            "SHIPMENT_DISPATCHED",
            "SHIPMENT_DELIVERED",
        }
    ),
    14: frozenset({"ITEM_PICKED", "ITEM_PACKED", "SHIPMENT_DISPATCHED", "SHIPMENT_DELIVERED"}),
    15: frozenset({"ITEM_PICKED", "ITEM_PACKED", "SHIPMENT_DISPATCHED", "SHIPMENT_DELIVERED"}),
}

#: Totals, hand-summed from the two tables above and asserted independently of them, so a
#: mistake in one table does not silently agree with a mistake in the other.
EXPECTED_EVENT_COUNTS: Final[dict[str, int]] = {
    "ORDER_PLACED": 15,
    "PAYMENT_REQUESTED": 12,
    "PAYMENT_APPROVED": 7,
    "PAYMENT_FAILED": 2,
    "PAYMENT_REVIEW_OPENED": 5,
    "FRAUD_SUSPECTED": 1,
    "ORDER_HELD": 2,
    "ORDER_CANCELED": 4,
    "INVENTORY_RESERVED": 10,
    "INVENTORY_RELEASED": 1,
    "INVENTORY_SHORTFALL_DETECTED": 2,
    "ITEM_PICKED": 16,
    "ITEM_PACKED": 16,
    "SHIPMENT_DISPATCHED": 16,
    "SHIPMENT_IN_TRANSIT": 10,
    "SHIPMENT_DELAYED": 4,
    "SHIPMENT_DELIVERED": 16,
    "ORDER_COMPLETED": 5,
    "ORDER_CLOSED": 2,
}

EXPECTED_EVENT_TOTAL: Final[int] = 146

#: The one event type the pack declares that no rule can witness. Its basis is "PROCESSING,
#: COMPLETE or CLOSED on an order whose history PASSED THROUGH a hold", and this source
#: carries one current status per order and no history at all.
EXPECTED_NEVER_EMITTED: Final[tuple[str, ...]] = ("ORDER_RELEASED",)

#: Distinct entities per type. Fifteen orders, twenty lines, one customer per order, three
#: products shared across the lines, and one each of the remaining types.
EXPECTED_ENTITY_COUNTS: Final[dict[str, int]] = {
    "CUSTOMER": 15,
    "DEPARTMENT": 1,
    "FULFILLMENT_SITE": 1,
    "MARKET_REGION": 1,
    "ORDER": 15,
    "ORDER_ITEM": 20,
    "PRODUCT": 3,
    "PRODUCT_CATEGORY": 1,
    "SHIPPING_MODE": 1,
}

#: Exactly one record disagrees with another about one attribute of one participant: the two
#: lines of order 2 name customer 502 and give it two different states.
EXPECTED_ATTRIBUTE_CONFLICTS: Final[int] = 1


def rows() -> tuple[dict[str, str], ...]:
    """Return the twenty raw records, in canonical row sequence.

    Raw, exactly as a delimited source would present them: every value is text and nothing
    has been transformed. The transforms are the mapping's business and are applied by
    `schema_mapper.clean_values`, so the fixture exercises that path rather than assuming it.
    """
    built: list[dict[str, str]] = []
    line_reference = 100
    for case in ORDERS:
        placed_day = case.reference
        for line in range(case.lines):
            line_reference += 1
            built.append(
                {
                    "Order Id": str(case.reference),
                    "Order Status": case.order_status,
                    "Type": "DEBIT",
                    # Every line of one order carries ONE order instant, as the real source
                    # does. Varying it per line would make each line a separate occurrence
                    # and would quietly defeat the deduplication this fixture exists to
                    # check -- which is how the first draft of this fixture was wrong.
                    "order date (DateOrders)": f"1/{placed_day}/2018 09:00",
                    "shipping date (DateOrders)": (
                        f"1/{placed_day + case.scheduled_days}/2018 09:00"
                    ),
                    "Days for shipment (scheduled)": str(case.scheduled_days),
                    "Days for shipping (real)": str(case.real_days),
                    "Delivery Status": case.delivery_status,
                    "Late_delivery_risk": "1" if case.real_days > case.scheduled_days else "0",
                    "Order Profit Per Order": "91.25",
                    "Benefit per order": "91.25",
                    "Order Item Id": str(line_reference),
                    "Order Item Quantity": "1",
                    "Order Item Product Price": "327.75",
                    "Order Item Discount": "13.11",
                    "Order Item Discount Rate": "0.04",
                    "Order Item Total": "314.64",
                    "Order Item Profit Ratio": "0.29",
                    "Customer Id": str(500 + case.reference),
                    "Customer Segment": "Consumer",
                    "Customer City": "Caguas",
                    # The one planted disagreement: order 2's second line names a different
                    # state for the same customer. One conflict, in one attribute, of one
                    # participant -- enough to exercise every ConflictPolicy and few enough
                    # that the count is checkable by eye.
                    "Customer State": ("NY" if case.reference == 2 and line == 1 else "PR"),
                    "Customer Country": "Puerto Rico",
                    "Customer Zipcode": "725",
                    "Product Card Id": str(700 + (line_reference % 3)),
                    "Product Name": "Instrument",
                    "Product Price": "327.75",
                    "Product Status": "0",
                    "Category Id": "73",
                    "Category Name": "Recreation",
                    "Department Id": "2",
                    "Department Name": "Leisure",
                    "Latitude": "18.25",
                    "Longitude": "-66.03",
                    "Market": "Pacific Asia",
                    "Order Region": "Southeast Asia",
                    "Order Country": "Indonesia",
                    "Order State": "Java Occidental",
                    "Order City": "Bekasi",
                    "Shipping Mode": "Standard Class",
                }
            )
    return tuple(built)
